/**
 * Shared Open Graph / Twitter share image used across every page, so social
 * previews look consistent everywhere. The image itself is generated by the
 * route handler at src/app/og/route.tsx and served at /og.
 *
 * Next.js merges metadata by overwriting (not deep-merging) the `openGraph`
 * and `twitter` objects, so any page that defines its own `openGraph` must
 * also include these images — import OG_IMAGES / OG_IMAGE_URL and spread them in.
 */
export const OG_IMAGE_URL = '/og';

export const OG_IMAGE = {
    url: OG_IMAGE_URL,
    width: 1200,
    height: 630,
    alt: 'Tahoe AI — search, enrich, and reach out from one calm, clear surface',
} as const;

export const OG_IMAGES = [OG_IMAGE];
